---
title: "Class6 R Functions"
author: "Shreya Sunkara"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# This is Heading 1.

This is my work from Class 6 in **BIMM 143**.

```{r}
#To demo a code chunk
plot(1:10)
```

## Practice reading files (again...)
```{r}
read.csv("Test1.txt")
read.table("Test2.txt",sep="$",header=TRUE)
read.table("Test3.txt",sep="",header=TRUE)
```
Sum of Inputs X + Y
```{r}
add <- function (x,y=1){
  x + y
}
```

```{r}
add(x=1,y=4)
add(1,4)
add(1)
add (c(1,2,3))
add(c(1,2,3),4)
```
New Function to Re-scale Data
```{r}
rescale <-function(x){
  rng <-range(x)
  ((x - rng[1])/(rng[2]-rng[1]))
}
```

```{r}
rescale(1:10)
```
Testing Function
```{r}
rescale(c(1,2,NA,3,10))

```
```{r}
x<-c(1,2,NA,3,10)
rng<-range(x)
rng
```
```{r}
x<-c(1,2,NA,3,10)
rng<-range(x,na.rm=TRUE)
rng
```

```{r}
rescale2<-function(x){
  rng<-range(x,na.rm=TRUE)
  (x-rng[1])/(rng[2]-rng[1])
}
```

```{r}
rescale2(c(1,2,NA,3,10))
```

