---
title: "Class8"
author: "Shreya Sunkara"
date: "10/24/2019"
output: html_document
---
## K means clustering
```{r}
#Generate some example data for clustering 
tmp<-c(rnorm(30,-3),rnorm(30,3))
x<-cbind(x=tmp,y=rev(tmp))
plot(x)
```
```{r}
k<-kmeans(x,centers=2,nstart=20)
k
```
```{r}
k$cluster
```
```{r}
k$size
```

```{r}
plot(x,col=k$cluster)
```
```{r}
dist_matrix<-dist(x)
hc<-hclust(d=dist_matrix)

plot(hc)
abline(h=2,col="red")
grps <- cutree(hc,k=3) 
grps
```
```{r}
#Step 1. Cenerate some example data for clustering
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
```
```{r}
table(grps,col)
```
lets do PCA with prcomp() function
```{r}
## You can also download this file from the class website!
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)
head(mydata) 
#doing PCA
pca<-prcomp(t(mydata),scale=TRUE)
#see what is returned by prcomp
attributes(pca)
#basic PC1 vs PC2 2-D plot
plot(pca$x[,1],pca$x[,2])
#percent variance is often more informative to look at
pca.var<-pca$sdev^2
pca.var.per<-round(pca.var/sum(pca.var)*100,1)
pca.var.per

barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
## A vector of colors for wt and ko samples
colvec <- colnames(mydata)
colvec[grep("wt", colvec)] <- "red"
colvec[grep("ko", colvec)] <- "blue"
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
```
```{r}
x <- read.csv("UK_Foods.csv")
x
#tells us number of rows and columns, respectively
dim(x)
```





